### ISSUE TITLE
[Veinminer] Replace chat toggle and UI with enchantment

### ISSUE THREAD

**Issue by Derpius** [TAServers/tas-mineclone2#15]
## Context

Toggling veinminer with a chat command is cumbersome and easy to forget to disable, and a keybind isn’t great gameplay

## Solution

- Add enchantments for veinminer 1, 2, and 3
- Each level breaks more blocks
- Veinminer only triggers when using a tool with a veinminer enchantment
- 

This has been discussed in the discord with Kilo, and neatly integrates the mod into gameplay with essentially perfect UX (people are already used to keeping a separate silk touch tool)

**Comment by yogwoggf** [comment]
Due to community vote, we're not going to go with crouch + sprint.

**Comment by yogwoggf** [comment]
Also, like the original plugin, I think it's worth having a global toggle which disables it completely. Thoughts? @Derpius

**Comment by Derpius** [comment]
Updated issue to match new ideal approach

**Comment by yogwoggf** [comment]
Fixed in [c3c2fc1](https://github.com/TAServers/tas-mineclone2/commit/c3c2fc10be87f071294f3a51dea4e2b0f982e854), forgot to tag this issue.
